# Site settings
title: tricky art
email: krishna1256@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9dc6c9 #fafbfa #49855c #582c0e #6f79bf #18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/saikrishna_sv
  - title: facebook
    url: https://facebook.com/saikrishna.sripada
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/saikrishna_sripada
  - title: github
    url: http://github.com/anhsirksai

# Postal address (add as many lines as necessary)
address:
  - line: 127 NBH
  - line: IIIT-H,
  - line: Hyderabad 500032 India.

#enabled gems(plugins) of my website.
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  -  jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty
